apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: redis-secret
  namespace: backend

spec:

  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: redis-secret

  data:

    - secretKey: REDIS_HOST

      remoteRef:
        key: file-storage-redis-secret
        property: REDIS_HOST

    - secretKey: REDIS_PORT

      remoteRef:
        key: file-storage-redis-secret
        property: REDIS_PORT
