pipeline {

    agent { label 'docker-agent' }

    environment {

        AWS_REGION = "ap-south-1"

        ACCOUNT_ID = '830279064856'

        REPO_NAME = 'backendapi'

        ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}"

        IMAGE_TAG = "${BUILD_NUMBER}"

        SONAR_SCANNER = tool 'sonar scanner'
    }

    stages {

        stage('Check Changes') {

            steps {

                script {

                    def changedFiles = sh(
                        script: "git diff --name-only HEAD~1 HEAD",
                        returnStdout: true
                    ).trim()

                    echo "Changed files:"
                    echo changedFiles

                    def backendChanged = changedFiles.split("\n").any {
                        it.startsWith("backend/")
                    }

                    if (!backendChanged) {

                        currentBuild.result = 'NOT_BUILT'

                        error("Skipping build: No backend changes detected")
                    }
                }
            }
        }

        stage('Install Dependencies') {

            steps {

                dir('backend') {

                    sh 'npm install'
                }
            }
        }

        stage('Run Tests + Coverage') {

            steps {

                dir('backend') {

                    sh 'npm run test:coverage'
                }
            }
        }

        stage('Dependency Scan') {

            steps {

                dir('backend') {

                    sh '''
                    npm audit --audit-level=high
                    '''
                }
            }
        }

        stage('SonarQube Scan') {

            steps {

                dir('backend') {

                    withSonarQubeEnv('sonarqube') {

                        sh '''
                        ${SONAR_SCANNER}/bin/sonar-scanner
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {

            steps {

                timeout(time: 5, unit: 'MINUTES') {

                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Trivy File System Scan') {

            steps {

                sh '''
                trivy fs backend \
                --severity CRITICAL \
                --exit-code 1
                '''
            }
        }

        stage('Build Docker Image') {

            steps {

                sh '''
                docker build \
                -t $ECR_REPO:$IMAGE_TAG \
                backend/

                docker tag \
                $ECR_REPO:$IMAGE_TAG \
                $ECR_REPO:latest
                '''
            }
        }

        stage('Trivy Image Scan') {

            steps {

                sh '''
                trivy image \
                --severity CRITICAL \
                --exit-code 1 \
                $ECR_REPO:$IMAGE_TAG
                '''
            }
        }

        stage('Login to AWS ECR') {

            steps {

                sh '''
                aws ecr get-login-password \
                --region $AWS_REGION \
                | docker login \
                --username AWS \
                --password-stdin \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
                '''
            }
        }

        stage('Push Docker Image') {

            steps {

                sh '''
                docker push $ECR_REPO:$IMAGE_TAG

                docker push $ECR_REPO:latest
                '''
            }
        }

        stage('Deploy Application') {

            agent { label 'jenkins-server' }

            steps {

                sh '''
                aws ecr get-login-password \
                --region $AWS_REGION \
                | docker login \
                --username AWS \
                --password-stdin \
                $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

                docker pull $ECR_REPO:latest

                docker stop backendapi || true
                docker rm backendapi || true

                docker run -d \
                  --name backendapi \
                  --restart always \
                  -p 3000:3000 \
                  --env-file /opt/backend.env \
                  $ECR_REPO:latest
                '''
            }
        }
    }

    post {

        success {

            echo 'Pipeline completed successfully'
        }

        failure {

            echo 'Pipeline failed'
        }

        always {

            sh '''
            docker image prune -af || true
            rm -rf *
            '''
        }
    }
}
