pipeline{
    agent { label 'docker-agent' }
  
    environment {
        AWS_REGION = 'ap-south-1'
        ACCOUNT_ID = '830279064856'
        REPO_NAME = 'backendapi'
        ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${REPO_NAME}"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

      stage("install"){

        steps {
            dir('backend') {
                sh 'npm install'
            }
        }
      }
      
      stage('Test + Coverage') {
            steps {
                dir('backend') {
                    sh 'npm run test:coverage'
                }
            }
       }

      stage('Dependency Scan') {
            steps {
                dir('backend') {
                    sh 'npm audit --audit-level=high'
                }
            }
        }
      
      stage('Trivy FS Scan') {
            steps {
                sh 'trivy fs --exit-code 1 --severity CRITICAL backend'
            }
         }

      stage('Build Image') {
            steps {
                sh '''
                cd backend
                docker build -t $ECR_REPO:$IMAGE_TAG .
                docker tag $ECR_REPO:$IMAGE_TAG $ECR_REPO:latest
                '''
            }
        }


    }




}