apiVersion: v1
kind: Secret

metadata:
  name: backend-secret

type: Opaque

stringData:
  DB_HOST: database-1.cxc4g6sj.ap-south-1.rds.amazonaws.com
  DB_NAME: files_db
  DB_USER: backend_user

  REDIS_HOST: clustercfg.redis.aps1.cache.amazonaws.com
  REDIS_PORT: "6379"

  S3_BUCKET: my-app-bucket

  AWS_REGION: ap-south-1
  Port: "3000"
