apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::830279064856:role/eksctl-filestorage-addon-iamserviceaccount-de-Role1-zEVVgATnADed
  creationTimestamp: "2026-05-11T22:05:53Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: backend-sa
  namespace: default
  resourceVersion: "15989"
  uid: 9d92faa8-5ce4-4297-9711-d03511a7e1fd