apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: test-alert
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
    - name: test
      rules:
        - alert: TestAlert
          expr: vector(1)
          for: 1m

          labels:
            severity: warning
            namespace: monitoring

          annotations:
            summary: Test Alert
            description: Alertmanager is working