apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: db-secret
  namespace: backend

spec:

  refreshInterval: 1m

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: db-secret

  data:

    - secretKey: DB_NAME

      remoteRef:
        key: filestorage-db-secret
        property: database

    - secretKey: DB_HOST

      remoteRef:
        key: filestorage-db-secret
        property: host

    - secretKey: DB_PORT

      remoteRef:
        key: filestorage-db-secret
        property: port

    - secretKey: DB_USER

      remoteRef:
        key: filestorage-db-secret
        property: username
    
