name: Test Self Hosted Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
env:
  AWS_REGION: ap-south-1
  ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  REPO_NAME: file-storage-backend
  ECR_REPO: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/file-storage-backend
  IMAGE_TAG: ${{ github.sha }}

jobs:

  test-runner:
    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: backend
        run: npm install

      - name: Run Tests
        working-directory: backend
        run: npm run test:coverage

      - name: NPM Audit
        working-directory: backend
        run: npm audit --audit-level=high
      
      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: backend
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REPO:$IMAGE_TAG \
            -t $ECR_REPO:latest \
            backend/

      - name: Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Push Docker Images
        run: |
          docker push $ECR_REPO:$IMAGE_TAG
          docker push $ECR_REPO:latest